### ISSUE TITLE
Detection as an API

### ISSUE THREAD

**Issue by Hyperclaw79** [arunponnusamy/gender-detection-keras#5]
# Feature Request
Rewrite this as a Class so that it can be used in other scripts to perform gander recognition on the go.

*P.S. Pretty good script btw. Really helpful.*

**Comment by ekinburak** [comment]
This could be nice  👍

**Comment by arunponnusamy** [comment]
Thanks for the suggestion. Will add it as a function call in [cvlib](http://cvlib.net).

**Comment by Hyperclaw79** [comment]
@arunponnusamy
Thank you for considering my suggestion sir. I have one more query:
Do the libraries used in the script support asynchronous model? I'm planning to integrate this into a discord bot in the future for autorole management based on user's avatar.
Since discord.py uses async, it would be wonderful if this task was non-blocking too.

**Comment by arunponnusamy** [comment]
Hello @Hyperclaw79 , have added gender detection as a function call in cvlib. Check it out. 
https://github.com/arunponnusamy/cvlib#gender-detection
I do not have much experience with async. I will look into it.

**Comment by Hyperclaw79** [comment]
Thank you 😄

>I do not have much experience with async. I will look into it.

And I do not have experience in ML. 😅 
Basically, what I meant is, whether the task of gender detection is blocking?
Would I be able to outsource each detection task as a seperate coroutine or does the second detection have to wait for the first one to complete?
Take a look at the builtin [Asyncio](https://docs.python.org/3/library/asyncio.html) library.

**Comment by Hyperclaw79** [comment]
Added it in the PR https://github.com/arunponnusamy/gender-detection-keras/pull/12. Async compatible as well.
